import { promises as fs } from "node:fs";
import path from "node:path";
import { pathExists } from "../state/fs";
import { toProjectRelative } from "../state/paths";
import type {
  DeploymentEnvDiagnostics,
  DeploymentEnvSource,
  DeploymentEnvVariable,
  DeploymentCodeProbe,
} from "./types";

type EnvAccumulator = Map<string, {
  required: boolean;
  sensitive: boolean;
  provided: boolean;
  generated: boolean;
  sources: Set<DeploymentEnvSource>;
  reason: string;
}>;

const ENV_EXAMPLE_FILES = [
  ".env.example",
  ".env.sample",
  ".env.local.example",
  ".env.template",
  ".env.dist",
];

const LOCAL_ENV_FILES = [
  ".env",
  ".env.local",
  ".env.development",
  ".env.production",
];

const SOURCE_EXTENSIONS = new Set([
  ".js",
  ".jsx",
  ".ts",
  ".tsx",
  ".mjs",
  ".cjs",
  ".py",
  ".go",
  ".java",
  ".cs",
  ".php",
  ".rb",
  ".yml",
  ".yaml",
  ".properties",
  ".toml",
]);

const IGNORED_DIRECTORIES = new Set([
  ".git",
  ".loom",
  "node_modules",
  "vendor",
  ".venv",
  "venv",
  "__pycache__",
  ".next",
  ".nuxt",
  ".turbo",
  ".vercel",
  "dist",
  "build",
  "coverage",
  "target",
  "bin",
  "obj",
  "tmp",
  "log",
  "storage",
]);

const OPTIONAL_ENV_NAMES = new Set([
  "CI",
  "DEBUG",
  "HOST",
  "HOSTNAME",
  "LOG_LEVEL",
  "NODE_ENV",
  "PORT",
  "RAILS_ENV",
  "RACK_ENV",
  "SERVER_PORT",
  "ASPNETCORE_ENVIRONMENT",
  "ASPNETCORE_URLS",
]);

export async function analyzeDeploymentEnvironment(input: {
  projectRoot: string;
  deploymentRoot: string;
  stack: DeploymentCodeProbe;
  generatedEnvironment: Record<string, string>;
  contractEnvironment?: {
    required: string[];
    optional: string[];
  };
}): Promise<DeploymentEnvDiagnostics> {
  const env: EnvAccumulator = new Map();

  for (const [name] of Object.entries(input.generatedEnvironment)) {
    addEnv(env, name, {
      required: false,
      provided: true,
      generated: true,
      source: generatedSourceFor(name, input.stack),
      reason: "Generated by loom for local deployment.",
    });
  }

  for (const name of input.contractEnvironment?.required ?? []) {
    addEnv(env, name, {
      required: !isOptionalEnvName(name),
      provided: Object.prototype.hasOwnProperty.call(input.generatedEnvironment, name),
      generated: Object.prototype.hasOwnProperty.call(input.generatedEnvironment, name),
      source: "runtime-contract",
      reason: "Required by RuntimeDeliveryContract.",
    });
  }

  for (const name of input.contractEnvironment?.optional ?? []) {
    addEnv(env, name, {
      required: false,
      provided: Object.prototype.hasOwnProperty.call(input.generatedEnvironment, name),
      generated: Object.prototype.hasOwnProperty.call(input.generatedEnvironment, name),
      source: "runtime-contract",
      reason: "Optional in RuntimeDeliveryContract.",
    });
  }

  for (const file of await readEnvFiles(input.projectRoot, input.deploymentRoot, ENV_EXAMPLE_FILES, true)) {
    for (const name of file.variables) {
      addEnv(env, name, {
        required: isRequiredEnvName(name, input.stack),
        provided: false,
        generated: false,
        source: "env-example",
        reason: `Referenced in ${file.path}.`,
      });
    }
  }

  const localEnvFiles = await readEnvFiles(input.projectRoot, input.deploymentRoot, LOCAL_ENV_FILES, false);
  for (const file of localEnvFiles) {
    for (const name of file.variables) {
      addEnv(env, name, {
        required: false,
        provided: false,
        generated: false,
        source: "local-env-file",
        reason: `Present in ${file.path}; value is not read or copied.`,
      });
    }
  }

  for (const reference of await scanSourceEnvReferences(input.projectRoot, input.deploymentRoot)) {
    addEnv(env, reference.name, {
      required: isRequiredEnvName(reference.name, input.stack),
      provided: false,
      generated: false,
      source: "source-code",
      reason: `Referenced in ${reference.path}.`,
    });
  }

  for (const frameworkVar of frameworkRequiredEnv(input.stack)) {
    addEnv(env, frameworkVar.name, {
      required: true,
      provided: false,
      generated: false,
      source: "framework",
      reason: frameworkVar.reason,
    });
  }

  for (const [name, value] of Object.entries(generatedPlaceholderEnvironment(input.stack, env))) {
    addEnv(env, name, {
      required: false,
      provided: true,
      generated: true,
      source: "generated-default",
      reason: "Generated as a local-only placeholder for a common framework secret.",
    });
    input.generatedEnvironment[name] = value;
  }

  const variables = [...env.entries()]
    .map(([name, value]) => toEnvVariable(name, value))
    .sort((left, right) => left.name.localeCompare(right.name));
  const provided = variables
    .filter((variable) => variable.provided || variable.generated)
    .map((variable) => variable.name)
    .sort();
  const missing = variables
    .filter((variable) => variable.required && !variable.provided && !variable.generated)
    .sort((left, right) => left.name.localeCompare(right.name));

  return {
    required: variables.filter((variable) => variable.required),
    referenced: variables,
    provided,
    generated: input.generatedEnvironment,
    missing,
    localEnvFiles,
    warnings: warningsFor(missing, localEnvFiles),
  };
}

export function generatedRuntimeEnvironment(stack: DeploymentCodeProbe): Record<string, string> {
  switch (stack.kind) {
    case "node":
      return {
        NODE_ENV: "production",
        PORT: String(stack.port),
      };
    case "python":
      return {
        PORT: String(stack.port),
      };
    case "go":
    case "java":
    case "dotnet":
    case "php":
    case "ruby":
      return {
        PORT: String(stack.port),
        ...(stack.kind === "ruby" ? { RAILS_ENV: "production", RACK_ENV: "production" } : {}),
        ...(stack.kind === "java" ? { SERVER_PORT: String(stack.port) } : {}),
        ...(stack.kind === "dotnet" ? { ASPNETCORE_URLS: `http://0.0.0.0:${stack.port}` } : {}),
      };
    default:
      return {};
  }
}

export function generatedDependencyEnvironment(stack: DeploymentCodeProbe): Record<string, string> {
  return Object.assign({}, ...stack.services.map((dependency) => dependency.connectionEnv));
}

function addEnv(
  accumulator: EnvAccumulator,
  name: string,
  input: {
    required: boolean;
    provided: boolean;
    generated: boolean;
    source: DeploymentEnvSource;
    reason: string;
  },
): void {
  const normalized = normalizeEnvName(name);
  if (!normalized) {
    return;
  }

  const current = accumulator.get(normalized) ?? {
    required: false,
    sensitive: isSensitiveEnvName(normalized),
    provided: false,
    generated: false,
    sources: new Set<DeploymentEnvSource>(),
    reason: input.reason,
  };
  current.required ||= input.required;
  current.provided ||= input.provided;
  current.generated ||= input.generated;
  current.sensitive ||= isSensitiveEnvName(normalized);
  current.sources.add(input.source);
  if (!current.reason.includes(input.reason)) {
    current.reason = `${current.reason} ${input.reason}`;
  }
  accumulator.set(normalized, current);
}

async function readEnvFiles(
  projectRoot: string,
  deploymentRoot: string,
  names: string[],
  example: boolean,
): Promise<Array<{ path: string; variables: string[]; ignored: boolean }>> {
  const files: Array<{ path: string; variables: string[]; ignored: boolean }> = [];
  const roots = uniquePaths([deploymentRoot, projectRoot]);

  for (const root of roots) {
    for (const name of names) {
      const filePath = path.join(root, name);
      if (!(await pathExists(filePath))) {
        continue;
      }

      const variables = parseEnvNames(await fs.readFile(filePath, "utf8"));
      files.push({
        path: toProjectRelative(projectRoot, filePath) || name,
        variables,
        ignored: !example,
      });
    }
  }

  return dedupeEnvFiles(files);
}

async function scanSourceEnvReferences(
  projectRoot: string,
  deploymentRoot: string,
): Promise<Array<{ name: string; path: string }>> {
  const references: Array<{ name: string; path: string }> = [];
  const files = dedupeStrings((await Promise.all(
    uniquePaths([deploymentRoot, projectRoot]).map((root) => collectSourceFiles(root, 0, 200)),
  )).flat());

  for (const file of files) {
    const raw = await fs.readFile(file, "utf8");
    for (const name of extractEnvReferences(raw)) {
      references.push({
        name,
        path: toProjectRelative(projectRoot, file),
      });
    }
  }

  return references;
}

async function collectSourceFiles(root: string, depth: number, limit: number): Promise<string[]> {
  if (depth > 4 || limit <= 0) {
    return [];
  }

  const entries = await safeReadDir(root);
  const files: string[] = [];
  for (const entry of entries) {
    if (files.length >= limit) {
      break;
    }

    const filePath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      if (!IGNORED_DIRECTORIES.has(entry.name)) {
        files.push(...await collectSourceFiles(filePath, depth + 1, limit - files.length));
      }
      continue;
    }

    if (entry.isFile() && SOURCE_EXTENSIONS.has(path.extname(entry.name))) {
      files.push(filePath);
    }
  }
  return files.slice(0, limit);
}

function extractEnvReferences(raw: string): string[] {
  const names = new Set<string>();
  const patterns = [
    /process\.env\.([A-Z][A-Z0-9_]*)/g,
    /process\.env\[['"]([A-Z][A-Z0-9_]*)['"]\]/g,
    /import\.meta\.env\.([A-Z][A-Z0-9_]*)/g,
    /os\.getenv\(['"]([A-Z][A-Z0-9_]*)['"]/g,
    /os\.environ\[['"]([A-Z][A-Z0-9_]*)['"]\]/g,
    /System\.getenv\(['"]([A-Z][A-Z0-9_]*)['"]\)/g,
    /Environment\.GetEnvironmentVariable\(['"]([A-Z][A-Z0-9_]*)['"]\)/g,
    /getenv\(['"]([A-Z][A-Z0-9_]*)['"]\)/g,
    /ENV\[['"]([A-Z][A-Z0-9_]*)['"]\]/g,
    /\$\{([A-Z][A-Z0-9_]*)(?::[^}]*)?\}/g,
    /\benv\(["']([A-Z][A-Z0-9_]*)["']\)/g,
  ];

  for (const pattern of patterns) {
    for (const match of raw.matchAll(pattern)) {
      names.add(match[1]);
    }
  }
  return [...names];
}

function parseEnvNames(raw: string): string[] {
  const names = new Set<string>();
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || trimmed.startsWith("export #")) {
      continue;
    }
    const match = trimmed.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/);
    if (match) {
      names.add(match[1]);
    }
  }
  return [...names].sort();
}

function frameworkRequiredEnv(stack: DeploymentCodeProbe): Array<{ name: string; reason: string }> {
  const vars: Array<{ name: string; reason: string }> = [];
  if (stack.framework === "laravel") {
    vars.push({ name: "APP_KEY", reason: "Laravel requires APP_KEY for encrypted cookies and app crypto." });
  }
  if (stack.framework === "rails") {
    vars.push({ name: "SECRET_KEY_BASE", reason: "Rails production boots commonly require SECRET_KEY_BASE." });
  }
  if (stack.framework === "django") {
    vars.push({ name: "SECRET_KEY", reason: "Django requires SECRET_KEY for production settings." });
  }
  return vars;
}

function generatedPlaceholderEnvironment(
  stack: DeploymentCodeProbe,
  env: EnvAccumulator,
): Record<string, string> {
  const generated: Record<string, string> = {};
  const candidates = ["NEXTAUTH_SECRET", "APP_KEY", "SECRET_KEY_BASE", "SECRET_KEY"];

  for (const name of candidates) {
    const variable = env.get(name);
    if (!variable?.required || variable.provided || variable.generated) {
      continue;
    }
    if (canGenerateLocalPlaceholder(name, stack)) {
      generated[name] = localPlaceholderFor(name);
    }
  }

  return generated;
}

function generatedSourceFor(name: string, stack: DeploymentCodeProbe): DeploymentEnvSource {
  if (Object.keys(generatedRuntimeEnvironment(stack)).includes(name)) {
    return "runtime-default";
  }
  return "dependency-service";
}

function canGenerateLocalPlaceholder(name: string, stack: DeploymentCodeProbe): boolean {
  if (name === "APP_KEY") {
    return stack.framework === "laravel";
  }
  if (name === "SECRET_KEY_BASE") {
    return stack.framework === "rails";
  }
  if (name === "SECRET_KEY") {
    return stack.framework === "django";
  }
  if (name === "NEXTAUTH_SECRET") {
    return stack.framework === "next";
  }
  return false;
}

function localPlaceholderFor(name: string): string {
  switch (name) {
    case "APP_KEY":
      return "base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    case "SECRET_KEY_BASE":
      return "loom-local-secret-key-base-change-me";
    case "SECRET_KEY":
      return "loom-local-django-secret-change-me";
    case "NEXTAUTH_SECRET":
      return "loom-local-nextauth-secret-change-me";
    default:
      return "loom-local-placeholder-change-me";
  }
}

function isRequiredEnvName(name: string, stack: DeploymentCodeProbe): boolean {
  if (isOptionalEnvName(name)) {
    return false;
  }
  if (stack.kind === "node" && name === "NODE_OPTIONS") {
    return false;
  }
  return isSensitiveEnvName(name) || isConnectionEnvName(name);
}

function isOptionalEnvName(name: string): boolean {
  return OPTIONAL_ENV_NAMES.has(name) ||
    name.startsWith("NEXT_PUBLIC_") ||
    name.startsWith("VITE_") ||
    name.startsWith("PUBLIC_");
}

function isSensitiveEnvName(name: string): boolean {
  return /(?:SECRET|TOKEN|PASSWORD|PASS|KEY|PRIVATE|CREDENTIAL|AUTH|JWT|SESSION|COOKIE)/.test(name);
}

function isConnectionEnvName(name: string): boolean {
  return /(?:DATABASE_URL|DATABASE_URI|DB_URL|DB_HOST|DB_NAME|DB_USER|POSTGRES_URL|POSTGRES_HOST|MYSQL_URL|MYSQL_HOST|MONGODB_URL|MONGODB_URI|MONGO_URL|REDIS_URL|REDIS_HOST|RABBITMQ_URL|AMQP_URL|ELASTICSEARCH_URL|S3_ENDPOINT|AWS_|SPRING_DATASOURCE_|SQLALCHEMY_DATABASE_URI|JDBC_)/.test(name);
}

function toEnvVariable(name: string, value: EnvAccumulator extends Map<string, infer V> ? V : never): DeploymentEnvVariable {
  return {
    name,
    required: value.required,
    sensitive: value.sensitive,
    provided: value.provided,
    generated: value.generated,
    sources: [...value.sources].sort(),
    reason: value.reason.trim(),
  };
}

function warningsFor(
  missing: DeploymentEnvVariable[],
  localEnvFiles: Array<{ path: string; variables: string[]; ignored: boolean }>,
): string[] {
  const warnings: string[] = [];
  if (missing.length > 0) {
    warnings.push(`Missing required environment variables: ${missing.map((variable) => variable.name).join(", ")}.`);
  }
  if (localEnvFiles.length > 0) {
    warnings.push("Local .env files were detected but values are not copied into generated images or Compose output.");
  }
  return warnings;
}

function normalizeEnvName(name: string): string | null {
  const normalized = name.trim();
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(normalized) ? normalized : null;
}

async function safeReadDir(directory: string): Promise<import("node:fs").Dirent[]> {
  try {
    return await fs.readdir(directory, { withFileTypes: true });
  } catch {
    return [];
  }
}

function uniquePaths(paths: string[]): string[] {
  return [...new Set(paths.map((value) => path.resolve(value)))];
}

function dedupeStrings(values: string[]): string[] {
  return [...new Set(values)];
}

function dedupeEnvFiles(
  files: Array<{ path: string; variables: string[]; ignored: boolean }>,
): Array<{ path: string; variables: string[]; ignored: boolean }> {
  const seen = new Set<string>();
  return files.filter((file) => {
    if (seen.has(file.path)) {
      return false;
    }
    seen.add(file.path);
    return true;
  });
}
